[package]
name = "cache-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.12"
tokio = { version = "1.1", features = ["full", "parking_lot"] }
tracing = "0.1.35"
